---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: consulserviceintentionssources.service.consul.k8s.nativechat.com
spec:
  group: service.consul.k8s.nativechat.com
  names:
    kind: ConsulServiceIntentionsSource
    listKind: ConsulServiceIntentionsSourceList
    plural: consulserviceintentionssources
    singular: consulserviceintentionssource
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description:
            ConsulServiceIntentionsSource is the Schema for the consulserviceintentionssources
            API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description:
                ConsulServiceIntentionsSourceSpec defines the desired state
                of ConsulServiceIntentionsSource
              properties:
                source:
                  properties:
                    action:
                      description:
                        Action is required for an L4 intention, and should
                        be set to one of "allow" or "deny" for the action that should
                        be taken if this intention matches a request.
                      type: string
                    description:
                      description:
                        Description for the intention. This is not used by
                        Consul, but is presented in API responses to assist tooling.
                      type: string
                    name:
                      description:
                        Name is the source of the intention. This is the
                        name of a Consul service. The service doesn't need to be registered.
                      type: string
                    namespace:
                      description: Namespace is the namespace for the Name parameter.
                      type: string
                    permissions:
                      description:
                        Permissions is the list of all additional L7 attributes
                        that extend the intention match criteria. Permission precedence
                        is applied top to bottom. For any given request the first permission
                        to match in the list is terminal and stops further evaluation.
                        As with L4 intentions, traffic that fails to match any of the
                        provided permissions in this intention will be subject to the
                        default intention behavior is defined by the default ACL policy.
                        This should be omitted for an L4 intention as it is mutually
                        exclusive with the Action field.
                      items:
                        properties:
                          action:
                            description:
                              Action is one of "allow" or "deny" for the
                              action that should be taken if this permission matches
                              a request.
                            type: string
                          http:
                            description:
                              HTTP is a set of HTTP-specific authorization
                              criteria.
                            properties:
                              header:
                                description:
                                  Header is a set of criteria that can match
                                  on HTTP request headers. If more than one is configured
                                  all must match for the overall match to apply.
                                items:
                                  properties:
                                    exact:
                                      description:
                                        Exact matches if the header with
                                        the given name is this value.
                                      type: string
                                    invert:
                                      description: Invert inverts the logic of the match.
                                      type: boolean
                                    name:
                                      description:
                                        Name is the name of the header to
                                        match.
                                      type: string
                                    prefix:
                                      description:
                                        Prefix matches if the header with
                                        the given name has this prefix.
                                      type: string
                                    present:
                                      description:
                                        Present matches if the header with
                                        the given name is present with any value.
                                      type: boolean
                                    regex:
                                      description:
                                        Regex matches if the header with
                                        the given name matches this pattern.
                                      type: string
                                    suffix:
                                      description:
                                        Suffix matches if the header with
                                        the given name has this suffix.
                                      type: string
                                  type: object
                                type: array
                              methods:
                                description:
                                  Methods is a list of HTTP methods for which
                                  this match applies. If unspecified all HTTP methods
                                  are matched. If provided the names must be a valid
                                  method.
                                items:
                                  type: string
                                type: array
                              pathExact:
                                description:
                                  PathExact is the exact path to match on
                                  the HTTP request path.
                                type: string
                              pathPrefix:
                                description:
                                  PathPrefix is the path prefix to match
                                  on the HTTP request path.
                                type: string
                              pathRegex:
                                description:
                                  PathRegex is the regular expression to
                                  match on the HTTP request path.
                                type: string
                            type: object
                        type: object
                      type: array
                  type: object
              required:
                - source
              type: object
            status:
              description:
                ConsulServiceIntentionsSourceStatus defines the observed
                state of ConsulServiceIntentionsSource
              properties:
                contentSha:
                  type: string
                updatedAt:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
